### ISSUE TITLE
نسخه 6 پکیج nuget

### ISSUE THREAD

**Issue by mohammadaminyza** [oroumand/Zamin#11]
سلام خسته نباشید.
پکیج نسخه .net 6 کی منتشر میشه؟

**Comment by mohammadaminyza** [comment]
یاد آوری : زده بودید قراره 

HammonServices Dependency removed from Constructor in the next release

حذف شه

**Comment by oroumand** [comment]
سلام
همین امروز منتشر شد. البته صرفا آپدیت به ورژن 6 و به روز رسانی‌های جزئی انجام شد. برخی از امکانات جدید مثل ویژگی‌هایی که در EF اضافه شده و ... باید به مرور پیاده سازی بشه! که ان شا الله به زودی آپدیت خواهد شد.
برای حذف اون مورد Services هم برای یک نسخه دیگه به دلیل مشکل داخلی در یکی از پروژه‌هایی که مورد استفاده قرار گرفته بود دست نگه داشتم!
