### ISSUE TITLE
اگه سرور ربیت بالا نباشه اپ به کلی بالا نمیاد

### ISSUE THREAD

**Issue by agaheman** [oroumand/Zamin#36]
https://github.com/oroumand/Zamin/blob/dcc3b82dbc69e2805a51bc322582d7df95e22920/src/04.%20EndPoints/Zamin.EndPoints.Web/StartupExtentions/AddZaminServicesExtentions.cs#L168

**Comment by oroumand** [comment]
در تنظیمات پروژه  MessageBusTypeName  را معادل Fake قرارد دهید مشکل برطرف می شود.
